apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admin-chart.fullname" . }}
  labels:
    {{- include "admin-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "admin-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "admin-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: REACT_APP_BACKEND_URI
              value: "http://arch.homework"
