apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notification-chart.fullname" . }}
  labels:
    {{- include "notification-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "notification-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "notification-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}-worker"
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          command: ["bash", "entrypoint.sh", "celery-worker"]
          env:
            - name: NOTIFICATION_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: notification-db-secret
                  key: NOTIFICATION_DATABASE_URI
            - name: NOTIFICATION_BROKER_URI
              value: "{{ .Values.brokerURI }}/3"
            - name: BROKER_URI
              value: "{{ .Values.brokerURI }}/4"
        - name: "{{ .Chart.Name }}-api"
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          command: ["bash", "entrypoint.sh", "api"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: NOTIFICATION_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: notification-db-secret
                  key: NOTIFICATION_DATABASE_URI
            - name: NOTIFICATION_BROKER_URI
              value: "{{ .Values.brokerURI }}/3"
            - name: BROKER_URI
              value: "{{ .Values.brokerURI }}/4"
