replicaCount: 2

fullnameOverride: "app"

image:
  repository: luwao/sp-app

service:
  type: NodePort
  port: 8000

postgresql:
  enabled: true
  name: postgres
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
