apiVersion: batch/v1
kind: Job
metadata:
  name: "order-db-job"
spec:
  template:
    metadata:
      name: "order-db-job"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job-for-order-service
        image: luwao/refactor-order:v9
        env:
          - name: ORDER_DATABASE_URI
            value: postgresql+psycopg2://myuser:passwd@postgres-order/myapp
        command:
          - sh
          - "-c"
          - |
            pwd
            alembic upgrade head
  backoffLimit: 0