apiVersion: batch/v1
kind: Job
metadata:
  name: "myapp"
spec:
  template:
    metadata:
      name: "myapp"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: luwao/sp-app:v1
        env:
          - name: DATABASE_URI
            value: postgresql+psycopg2://myuser:passwd@postgres/myapp
        command:
          - sh
          - "-c"
          - |
            pwd
            alembic upgrade head
  backoffLimit: 0