replicaCount: 1

fullnameOverride: "payment"

image:
  repository: luwao/eda-payment-service

service:
  type: NodePort
  port: 8000

postgresql:
  enabled: true
  name: postgres
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp

brokerURI: "redis://redis:$(REDIS_SERVICE_PORT)/1"
